version: '3.6'

services:
  db:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: riviere
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  app:
    image: node:16
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 1234:1234
    command: npm run dev

  api:
    image: node:16
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: node ./api.mjs
    environment:
      JWT_SECRET: ${JWT_SECRET}

  prisma-studio:
    image: node:16
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 5555:5555
    command: npx prisma studio
